# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedores',
            name='email',
            field=models.EmailField(default='user@domain.es', max_length=254),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='web',
            field=models.URLField(default=''),
        ),
    ]
