# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_auto_20161111_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='precio_comra',
            new_name='precio_compra',
        ),
    ]
