# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_clientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Proveedores', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Tipo_productos', verbose_name='Tipo de Producto'),
        ),
    ]
