# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0017_auto_20161111_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renovations',
            name='fecha_proxima_renovacion',
            field=models.DateField(verbose_name='Proxima renovacion'),
        ),
    ]
