# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0018_auto_20161111_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renovations',
            name='fecha_proxima_renovacion',
        ),
    ]
