# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0019_remove_renovations_fecha_proxima_renovacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Renovations',
            new_name='Renovaciones',
        ),
    ]
